name: CI - QuantTrading

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Docker Compose Up
        run: |
          docker compose -f docker/docker-compose.yml up -d
          # Aguarda os containers ficarem healthy (máx 60s)
          docker compose -f docker/docker-compose.yml ps
          for i in {1..12}; do
            unhealthy=$(docker compose -f docker/docker-compose.yml ps | grep -c unhealthy || true)
            [ "$unhealthy" -eq 0 ] && break
            echo "Aguardando containers ficarem healthy..."
            sleep 5
          done
          docker compose -f docker/docker-compose.yml ps

      - name: Smoke Test Redis
        run: |
          docker run --network qt_local --rm redis:7-alpine redis-cli -h redis ping

      - name: Smoke Test ClickHouse
        run: |
          docker run --network qt_local --rm clickhouse/clickhouse-server:23.5 clickhouse-client --host clickhouse --query "SELECT 1"

      # - name: Lint (black, isort, pylint)
      #   run: |
      #     black --check .
      #     isort --check-only .
      #     pylint src/ || true   # não falha a pipeline por warning

      - name: Run tests
        run: |
          pytest -n auto --maxfail=1 --disable-warnings

      - name: Docker Compose Down
        if: always()
        run: |
          docker compose -f docker/docker-compose.yml down
